### PR TITLE
Logitech Harmony Support

### PR DESCRIPTION
**Pull request by Hackworth**
Support for Logitech Harmony Home Control, doesn't seem to break discovery for the Echo.

### CODE REVIEW

**Comment by emiliosic** [comment]
That would be great; I also have both devices

**Comment by digitaldan** [comment]
+1 for me too

**Comment by Hackworth** [comment]
@emiliosic @digitaldan Would you care to test it out? 
```
git clone https://github.com/Hackworth/amazon-echo-ha-bridge.git
sudo apt-get install maven
```
Copy your `data` directory into `amazon-echo-ha-bridge`
```
cd amazon-echo-ha-bridge
mvn spring-boot:run -Dupnp.config.address=IPADDRESS
```

**Comment by digitaldan** [comment]
Yep I just built it off you PR, I'll let you know how it goes.

**Comment by digitaldan** [comment]
@Hackworth this looks good on my system, the logitech harmony and echo can both discover discover devices now.

**Comment by armzilla** [comment]
merged PR #17 into the master, pre-release 0.2.0 created

**Pull request merged**
