### PR TITLE
Smart things raspberry mods

### PR DESCRIPTION
**Pull request by gouldner**
These are my mods to make your bridge work directly with the SmartThings hub.

My readme.md file describes how it works.

Basically my mod allows you to configure from the bridge and it updates your list based on what you select.

I based on version v0.1.2 and have not merged with v0.1.3 yet.  I placed on a branch for this push request so you can decide to keep as a feature or merge or not accept, that's up to you.

Let me know if you have any questions.

### CODE REVIEW

**Comment by mwkrieger** [comment]
Hi, I'd love to be able to add PI support to this fantastic bridge so I don't have to run this on my mac anymore, but I'm unsure on how to compile this so I can get a JAR to run. 

Would you be able to point me to directions to do this? I would greatly appreciate it.

**Comment by gouldner** [comment]
mwkrieger
The version 0.1.2 jar is in the repo now you can just use that.
If you want the version 0.1.3 version you need to build with mvn and java 8
I want to upload the 0.1.3 jar but I am traveling and have a lousy internet connection right now so it keeps failing.  I have to do it next week or when I can get a better connection.

**Comment by mwkrieger** [comment]
Thanks so much! I'll give it a try.

**Comment by shanekuz** [comment]
any chance of having this call a script on the box so its simple to control anything?  I have telnet scripts to turn on my amps and HTTP commands to turn on my Mi Light bulbs and projector etc and having this with the ability to do that would make it very usable.  Sorry if it does that already but im just starting with this as I just got my echo.

**Comment by gouldner** [comment]
Don't understand.  This code is intended to act as a bridge between Amazon Echo and Smart Things.  Having it call a script to control devices seems like a unrelated modification.  Of course if you feel the code is a good starting point for such a mod then feel free to fork the project and modify it.

**Comment by shanekuz** [comment]
Sorry misunderstood how it worked, have it working fine now with voxcommander controlling my mi lights and stereo system.  Thanks for the awesome app.  Voxcommander had poor voice recognition and robot speech responses I found but with echo fronting it the solution is amazing.  All running on windows for anyone that cares.

**Comment by maddox** [comment]
Echo works directly with SmartThings now. Unless I'm missing something, I think this branch is redundant at this point.

**Comment by gouldner** [comment]
Yea pretty much but it came in handy before the Echo was updated with ST integration.    I think the entire project isn't really needed anymore.

**Comment by maddox** [comment]
> I think the entire project isn't really needed anymore.

Well, it is if you have one of the many other unsupported systems. Hell, I use this for Wink and Wink IS supported. But with the bridge, I can actually DIM my lights, lol.

I also use it to turn off things like my TV via the Harmony Hub. It's a general purpose project that provides a ton of value.

**Comment by audiofreak9** [comment]
I agree the bride is still useful, not for ST now of course, but I use it to control my X10 stuff, which will NEVER be integrated into the Echo because my X10 control is through a custom PHP script I wrote that resides on the same RPi as the bridge.

**Comment by maddox** [comment]
:+1: Yup. It's pretty great.

**Comment by gouldner** [comment]
Cool, I plan to drop my fork since I have no use for it and nothing of value to add to it.  Thanks armzilla it was nice to have ST integration early on my Echo !

**Comment by armzilla** [comment]
Yep!  I was expecting amazon to do this at some point.  I wish I could say it was due to this project and the excitement from y'all but I think it made sense right off the gate.

**Pull request closed without merging**
